name: Scrape latest outage data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 */1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://data.usatoday.com/media/jsons/power/active/national_powerout_slider_data.js?v=2025220932
    - name: Commit and push if it changed
      run: |-
        git config user.name "outage-data"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data as of ${timestamp}" || exit 0
        git push
