name: Scrape latest outage data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 12 */1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up dynamic parameter
      id: set-param
      run: |-
        # This recreates: y + m + d + h + mi format from JavaScript
        YEAR=$(date +%Y)
        # Note: date command months are 1-12, but JavaScript months are 0-11
        MONTH=$(date +%-m)
        MONTH=$((MONTH - 1))  # Adjust to match JavaScript's 0-based month
        DAY=$(date +%-d)
        HOUR=$(date +%-H)
        MINUTE=$(date +%-M)
        TIMESTAMP="${YEAR}${MONTH}${DAY}${HOUR}${MINUTE}"
        echo "TIMESTAMP_PARAM=$TIMESTAMP" >> $GITHUB_ENV
        echo "- Timestamp: $TIMESTAMP_PARAM" >> $GITHUB_STEP_SUMMARY   
    - name: Fetch latest data
      run: |-
        curl -o us-outage.js https://data.usatoday.com/media/jsons/power/active/national_powerout_slider_data.js?v=${{ env.TIMESTAMP_PARAM }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "outage-data"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data as of ${timestamp}" || exit 0
        git push
